spring:
  application:
    name: Quiz

  datasource:
    url: jdbc:mariadb://localhost:3306/quizgame
    username: root
    password: us3Datt921
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
    jwt:
      secret: c2VkdWVmaDQyXGFzZHBxLC5jc2RjbXNvaWRISVdlZG9xaW5VV1dISTFbMSxzYS5jYWV3ZjEzVVljYXM=
      access: 3600000
      refresh: 2592000000